#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
NC='\033[0m' # No Color

printf "\n${GREEN}Running Prettier on files...${NC}"
pnpm run pretty

printf "\n${GREEN}Checking for ESLint rule violations...${NC}"
pnpm run lint
